# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\copperdai\Desktop\Inventory_swim_store_PhungDaiDong\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1431, 817)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Logo-EAUT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.widget_2.setStyleSheet("\n"
"background-color: rgb(255, 129, 2);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_home = QtWidgets.QPushButton(self.widget_3)
        self.button_home.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"    border-radius:4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-radius:4px;\n"
"background-color: rgb(255, 119, 0);\n"
"}\n"
"")
        self.button_home.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase)
        self.button_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_home.setIcon(icon1)
        self.button_home.setIconSize(QtCore.QSize(38, 38))
        self.button_home.setCheckable(True)
        self.button_home.setAutoExclusive(True)
        self.button_home.setFlat(True)
        self.button_home.setObjectName("button_home")
        self.verticalLayout.addWidget(self.button_home)
        self.button_add = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_add.setFont(font)
        self.button_add.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"    border-radius:4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-radius:4px;\n"
"background-color: rgb(255, 119, 0);\n"
"}\n"
"")
        self.button_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/addItem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add.setIcon(icon2)
        self.button_add.setIconSize(QtCore.QSize(38, 38))
        self.button_add.setCheckable(True)
        self.button_add.setAutoExclusive(True)
        self.button_add.setFlat(True)
        self.button_add.setObjectName("button_add")
        self.verticalLayout.addWidget(self.button_add)
        self.button_search_tab = QtWidgets.QPushButton(self.widget_3)
        self.button_search_tab.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"    border-radius:4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border-radius:4px;\n"
"background-color: rgb(255, 119, 0);\n"
"}\n"
"")
        self.button_search_tab.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/specialFeature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_search_tab.setIcon(icon3)
        self.button_search_tab.setIconSize(QtCore.QSize(38, 38))
        self.button_search_tab.setCheckable(True)
        self.button_search_tab.setAutoExclusive(True)
        self.button_search_tab.setFlat(True)
        self.button_search_tab.setObjectName("button_search_tab")
        self.verticalLayout.addWidget(self.button_search_tab)
        self.verticalLayout_2.addWidget(self.widget_3)
        spacerItem = QtWidgets.QSpacerItem(20, 567, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Icons/Logo-EAUT.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_main = QtWidgets.QWidget(self.centralwidget)
        self.widget_main.setAutoFillBackground(False)
        self.widget_main.setStyleSheet("")
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_tab = QtWidgets.QTabWidget(self.widget_main)
        self.main_tab.setMinimumSize(QtCore.QSize(1, 1))
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setAutoFillBackground(False)
        self.main_tab.setStyleSheet("QTabWidget{\n"
"border:none;\n"
"}")
        self.main_tab.setUsesScrollButtons(True)
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(False)
        self.main_tab.setMovable(False)
        self.main_tab.setTabBarAutoHide(False)
        self.main_tab.setObjectName("main_tab")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_home)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.tab_home)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 7, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_kho1 = QtWidgets.QFrame(self.widget_10)
        self.frame_kho1.setStyleSheet("QFrame{\n"
"    border: 1px solid grey;\n"
"    border-radius:3px;\n"
"}\n"
"")
        self.frame_kho1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kho1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kho1.setObjectName("frame_kho1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_kho1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_kho1)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.label_count_products = QtWidgets.QLabel(self.frame_kho1)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_count_products.setFont(font)
        self.label_count_products.setStyleSheet("\n"
"border: none;")
        self.label_count_products.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count_products.setObjectName("label_count_products")
        self.verticalLayout_8.addWidget(self.label_count_products)
        self.verticalLayout_7.addWidget(self.frame_kho1)
        self.horizontalLayout_4.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.widget_11)
        self.frame_3.setStyleSheet("QFrame{\n"
"    border: 1px solid grey;\n"
"    border-radius:3px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setContentsMargins(7, 0, 7, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.label_count_out_stock = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_count_out_stock.setFont(font)
        self.label_count_out_stock.setAutoFillBackground(False)
        self.label_count_out_stock.setStyleSheet("\n"
"border: none;")
        self.label_count_out_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count_out_stock.setObjectName("label_count_out_stock")
        self.verticalLayout_10.addWidget(self.label_count_out_stock)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.horizontalLayout_4.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_5)
        self.widget_12.setMinimumSize(QtCore.QSize(1, 1))
        self.widget_12.setAutoFillBackground(False)
        self.widget_12.setStyleSheet("QWidget{\n"
"        \n"
"    \n"
"        background-repeat: no-repeat; \n"
"        background-position: center;\n"
"    }\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_12.setContentsMargins(7, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_image = QtWidgets.QLabel(self.widget_12)
        self.label_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QtCore.QSize(426, 365))
        self.label_image.setMaximumSize(QtCore.QSize(6666666, 66666))
        self.label_image.setStyleSheet("border: 1px solid grey;\n"
"    border-radius:3px;")
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_12.addWidget(self.label_image)
        self.horizontalLayout_4.addWidget(self.widget_12)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.line_3 = QtWidgets.QFrame(self.widget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_9)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(120, 80))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton = QtWidgets.QRadioButton(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.horizontalLayout_3.addWidget(self.widget_9, 0, QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.widget_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setAutoFillBackground(False)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.layout_sodo = QtWidgets.QHBoxLayout()
        self.layout_sodo.setObjectName("layout_sodo")
        self.horizontalLayout_14.addLayout(self.layout_sodo)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.main_tab.addTab(self.tab_home, "")
        self.tab_add_product = QtWidgets.QWidget()
        self.tab_add_product.setObjectName("tab_add_product")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_add_product)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.tab_add_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(240, 16777215))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.lineEditName = QtWidgets.QLineEdit(self.widget)
        self.lineEditName.setGeometry(QtCore.QRect(0, 70, 231, 41))
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditName.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEdit_Material = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Material.setGeometry(QtCore.QRect(0, 220, 231, 41))
        self.lineEdit_Material.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Material.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEdit_Material.setFont(font)
        self.lineEdit_Material.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.lineEdit_Material.setObjectName("lineEdit_Material")
        self.lineEdit_Description = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Description.setGeometry(QtCore.QRect(0, 170, 231, 41))
        self.lineEdit_Description.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Description.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEdit_Description.setFont(font)
        self.lineEdit_Description.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.lineEdit_Brand = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Brand.setGeometry(QtCore.QRect(0, 270, 231, 41))
        self.lineEdit_Brand.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Brand.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEdit_Brand.setFont(font)
        self.lineEdit_Brand.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.lineEdit_Brand.setObjectName("lineEdit_Brand")
        self.comboBox_category = QtWidgets.QComboBox(self.widget)
        self.comboBox_category.setGeometry(QtCore.QRect(0, 320, 231, 41))
        self.comboBox_category.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_category.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.comboBox_category.setFont(font)
        self.comboBox_category.setStyleSheet("\n"
"\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.comboBox_category.setObjectName("comboBox_category")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.lineEdit_type = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_type.setGeometry(QtCore.QRect(0, 120, 231, 41))
        self.lineEdit_type.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_type.setMaximumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEdit_type.setFont(font)
        self.lineEdit_type.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.horizontalLayout_5.addWidget(self.widget)
        self.widget_13 = QtWidgets.QWidget(self.tab_add_product)
        self.widget_13.setStyleSheet("")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.widget_13)
        self.frame.setStyleSheet("\n"
"border-radius: 9px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 65))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 65))
        self.widget_14.setStyleSheet("")
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_16 = QtWidgets.QWidget(self.widget_14)
        self.widget_16.setMinimumSize(QtCore.QSize(171, 0))
        self.widget_16.setMaximumSize(QtCore.QSize(171, 16777215))
        self.widget_16.setStyleSheet("")
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.pushButtonADDColor = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonADDColor.sizePolicy().hasHeightForWidth())
        self.pushButtonADDColor.setSizePolicy(sizePolicy)
        self.pushButtonADDColor.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButtonADDColor.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonADDColor.setIcon(icon4)
        self.pushButtonADDColor.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonADDColor.setCheckable(False)
        self.pushButtonADDColor.setChecked(False)
        self.pushButtonADDColor.setFlat(False)
        self.pushButtonADDColor.setObjectName("pushButtonADDColor")
        self.horizontalLayout_7.addWidget(self.pushButtonADDColor)
        self.pushButton_MINUScolor = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_MINUScolor.sizePolicy().hasHeightForWidth())
        self.pushButton_MINUScolor.setSizePolicy(sizePolicy)
        self.pushButton_MINUScolor.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_MINUScolor.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_MINUScolor.setIcon(icon5)
        self.pushButton_MINUScolor.setObjectName("pushButton_MINUScolor")
        self.horizontalLayout_7.addWidget(self.pushButton_MINUScolor)
        self.pushButton_ADDColors = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ADDColors.sizePolicy().hasHeightForWidth())
        self.pushButton_ADDColors.setSizePolicy(sizePolicy)
        self.pushButton_ADDColors.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_ADDColors.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/icons8-color-swatch-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ADDColors.setIcon(icon6)
        self.pushButton_ADDColors.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_ADDColors.setObjectName("pushButton_ADDColors")
        self.horizontalLayout_7.addWidget(self.pushButton_ADDColors)
        self.horizontalLayout_6.addWidget(self.widget_16)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.widget_17 = QtWidgets.QWidget(self.widget_14)
        self.widget_17.setMinimumSize(QtCore.QSize(131, 0))
        self.widget_17.setMaximumSize(QtCore.QSize(131, 16777215))
        self.widget_17.setStyleSheet("")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_ADDsize = QtWidgets.QPushButton(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ADDsize.sizePolicy().hasHeightForWidth())
        self.pushButton_ADDsize.setSizePolicy(sizePolicy)
        self.pushButton_ADDsize.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_ADDsize.setText("")
        self.pushButton_ADDsize.setIcon(icon4)
        self.pushButton_ADDsize.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_ADDsize.setCheckable(False)
        self.pushButton_ADDsize.setChecked(False)
        self.pushButton_ADDsize.setFlat(False)
        self.pushButton_ADDsize.setObjectName("pushButton_ADDsize")
        self.horizontalLayout_8.addWidget(self.pushButton_ADDsize)
        self.pushButton_MINUSsize = QtWidgets.QPushButton(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_MINUSsize.sizePolicy().hasHeightForWidth())
        self.pushButton_MINUSsize.setSizePolicy(sizePolicy)
        self.pushButton_MINUSsize.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_MINUSsize.setText("")
        self.pushButton_MINUSsize.setIcon(icon5)
        self.pushButton_MINUSsize.setObjectName("pushButton_MINUSsize")
        self.horizontalLayout_8.addWidget(self.pushButton_MINUSsize)
        self.label_6 = QtWidgets.QLabel(self.widget_17)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_6.addWidget(self.widget_17)
        self.verticalLayout_12.addWidget(self.widget_14, 0, QtCore.Qt.AlignVCenter)
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setStyleSheet("border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.tableView.setIconSize(QtCore.QSize(150, 150))
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setDefaultSectionSize(125)
        self.verticalLayout_12.addWidget(self.tableView)
        self.widget_15 = QtWidgets.QWidget(self.frame)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout.setContentsMargins(0, 12, 0, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_18 = QtWidgets.QWidget(self.widget_15)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOK.sizePolicy().hasHeightForWidth())
        self.pushButtonOK.setSizePolicy(sizePolicy)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(110, 58))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\copperdai\\Desktop\\Inventory_swim_store_PhungDaiDong\\../../.designer/Icons/stick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOK.setIcon(icon7)
        self.pushButtonOK.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_9.addWidget(self.pushButtonOK)
        self.pushButtonClearData = QtWidgets.QPushButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClearData.sizePolicy().hasHeightForWidth())
        self.pushButtonClearData.setSizePolicy(sizePolicy)
        self.pushButtonClearData.setMinimumSize(QtCore.QSize(110, 58))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.pushButtonClearData.setFont(font)
        self.pushButtonClearData.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\copperdai\\Desktop\\Inventory_swim_store_PhungDaiDong\\../../.designer/Icons/face-id.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClearData.setIcon(icon8)
        self.pushButtonClearData.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonClearData.setObjectName("pushButtonClearData")
        self.horizontalLayout_9.addWidget(self.pushButtonClearData)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.gridLayout.addWidget(self.widget_18, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.widget_15, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.frame)
        self.horizontalLayout_5.addWidget(self.widget_13)
        self.main_tab.addTab(self.tab_add_product, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_20 = QtWidgets.QWidget(self.tab_search)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_19 = QtWidgets.QWidget(self.widget_20)
        self.widget_19.setStyleSheet("")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_11.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_keysearch = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_keysearch.sizePolicy().hasHeightForWidth())
        self.lineEdit_keysearch.setSizePolicy(sizePolicy)
        self.lineEdit_keysearch.setMinimumSize(QtCore.QSize(1, 1))
        self.lineEdit_keysearch.setMaximumSize(QtCore.QSize(60000, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.lineEdit_keysearch.setFont(font)
        self.lineEdit_keysearch.setStyleSheet("border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"        border-radius:4px")
        self.lineEdit_keysearch.setObjectName("lineEdit_keysearch")
        self.horizontalLayout_11.addWidget(self.lineEdit_keysearch)
        self.button_search_2 = QtWidgets.QPushButton(self.widget_19)
        self.button_search_2.setMinimumSize(QtCore.QSize(41, 41))
        self.button_search_2.setMaximumSize(QtCore.QSize(41, 41))
        self.button_search_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.button_search_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/800px-Search_Icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_search_2.setIcon(icon9)
        self.button_search_2.setObjectName("button_search_2")
        self.horizontalLayout_11.addWidget(self.button_search_2)
        self.horizontalLayout_10.addWidget(self.widget_19)
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.button_save_product_edit = QtWidgets.QPushButton(self.widget_20)
        self.button_save_product_edit.setMinimumSize(QtCore.QSize(43, 43))
        self.button_save_product_edit.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button_save_product_edit.setFont(font)
        self.button_save_product_edit.setToolTipDuration(0)
        self.button_save_product_edit.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.button_save_product_edit.setObjectName("button_save_product_edit")
        self.horizontalLayout_10.addWidget(self.button_save_product_edit)
        self.verticalLayout_13.addWidget(self.widget_20, 0, QtCore.Qt.AlignTop)
        self.tableWidget_product = QtWidgets.QTableWidget(self.tab_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_product.sizePolicy().hasHeightForWidth())
        self.tableWidget_product.setSizePolicy(sizePolicy)
        self.tableWidget_product.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(13)
        self.tableWidget_product.setFont(font)
        self.tableWidget_product.setAcceptDrops(False)
        self.tableWidget_product.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_product.setAutoFillBackground(False)
        self.tableWidget_product.setStyleSheet("")
        self.tableWidget_product.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_product.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_product.setAutoScrollMargin(16)
        self.tableWidget_product.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget_product.setAlternatingRowColors(True)
        self.tableWidget_product.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_product.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_product.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget_product.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_product.setShowGrid(True)
        self.tableWidget_product.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_product.setCornerButtonEnabled(True)
        self.tableWidget_product.setRowCount(0)
        self.tableWidget_product.setObjectName("tableWidget_product")
        self.tableWidget_product.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(6, item)
        self.tableWidget_product.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_product.horizontalHeader().setDefaultSectionSize(185)
        self.tableWidget_product.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_product.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_product.verticalHeader().setVisible(False)
        self.tableWidget_product.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_product.verticalHeader().setDefaultSectionSize(50)
        self.verticalLayout_13.addWidget(self.tableWidget_product, 0, QtCore.Qt.AlignHCenter)
        self.main_tab.addTab(self.tab_search, "")
        self.tab_item = QtWidgets.QWidget()
        self.tab_item.setObjectName("tab_item")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_item)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_24 = QtWidgets.QWidget(self.tab_item)
        self.widget_24.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.button_previous_2 = QtWidgets.QPushButton(self.widget_24)
        self.button_previous_2.setMinimumSize(QtCore.QSize(43, 43))
        self.button_previous_2.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button_previous_2.setFont(font)
        self.button_previous_2.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.button_previous_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_previous_2.setIcon(icon10)
        self.button_previous_2.setObjectName("button_previous_2")
        self.horizontalLayout_15.addWidget(self.button_previous_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.widget_25 = QtWidgets.QWidget(self.widget_24)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_new_item = QtWidgets.QPushButton(self.widget_25)
        self.pushButton_new_item.setMinimumSize(QtCore.QSize(43, 43))
        self.pushButton_new_item.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_new_item.setFont(font)
        self.pushButton_new_item.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_new_item.setObjectName("pushButton_new_item")
        self.horizontalLayout_16.addWidget(self.pushButton_new_item)
        self.pushButton_save_edit_item = QtWidgets.QPushButton(self.widget_25)
        self.pushButton_save_edit_item.setMinimumSize(QtCore.QSize(43, 43))
        self.pushButton_save_edit_item.setMaximumSize(QtCore.QSize(41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_save_edit_item.setFont(font)
        self.pushButton_save_edit_item.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"        border-radius:4px\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_save_edit_item.setObjectName("pushButton_save_edit_item")
        self.horizontalLayout_16.addWidget(self.pushButton_save_edit_item)
        self.horizontalLayout_15.addWidget(self.widget_25)
        self.verticalLayout_14.addWidget(self.widget_24, 0, QtCore.Qt.AlignTop)
        self.tableWidget_item = QtWidgets.QTableWidget(self.tab_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_item.sizePolicy().hasHeightForWidth())
        self.tableWidget_item.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(13)
        self.tableWidget_item.setFont(font)
        self.tableWidget_item.setAcceptDrops(False)
        self.tableWidget_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_item.setAutoFillBackground(False)
        self.tableWidget_item.setStyleSheet("")
        self.tableWidget_item.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_item.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_item.setAutoScrollMargin(10)
        self.tableWidget_item.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget_item.setAlternatingRowColors(False)
        self.tableWidget_item.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_item.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_item.setIconSize(QtCore.QSize(170, 170))
        self.tableWidget_item.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget_item.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_item.setShowGrid(True)
        self.tableWidget_item.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_item.setCornerButtonEnabled(True)
        self.tableWidget_item.setRowCount(0)
        self.tableWidget_item.setColumnCount(6)
        self.tableWidget_item.setObjectName("tableWidget_item")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_item.setHorizontalHeaderItem(5, item)
        self.tableWidget_item.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_item.horizontalHeader().setDefaultSectionSize(185)
        self.tableWidget_item.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_item.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_item.verticalHeader().setVisible(False)
        self.tableWidget_item.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_item.verticalHeader().setDefaultSectionSize(180)
        self.verticalLayout_14.addWidget(self.tableWidget_item, 0, QtCore.Qt.AlignHCenter)
        self.main_tab.addTab(self.tab_item, "")
        self.horizontalLayout_2.addWidget(self.main_tab, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.widget_main, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inventory software"))
        self.label.setText(_translate("MainWindow", "Count of all products"))
        self.label_count_products.setText(_translate("MainWindow", "200088"))
        self.label_2.setText(_translate("MainWindow", "Products out of stock"))
        self.label_count_out_stock.setText(_translate("MainWindow", "100"))
        self.radioButton.setText(_translate("MainWindow", "Quantity"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_home), _translate("MainWindow", "home"))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "Name >9"))
        self.lineEdit_Material.setPlaceholderText(_translate("MainWindow", "Material"))
        self.lineEdit_Description.setPlaceholderText(_translate("MainWindow", "Description"))
        self.lineEdit_Brand.setPlaceholderText(_translate("MainWindow", "Brand"))
        self.comboBox_category.setCurrentText(_translate("MainWindow", "---select accessory---"))
        self.comboBox_category.setItemText(0, _translate("MainWindow", "---select accessory---"))
        self.comboBox_category.setItemText(1, _translate("MainWindow", "Swim fins"))
        self.comboBox_category.setItemText(2, _translate("MainWindow", "Swim paddles"))
        self.comboBox_category.setItemText(3, _translate("MainWindow", "Swim goggles"))
        self.comboBox_category.setItemText(4, _translate("MainWindow", "Snorkel mask"))
        self.comboBox_category.setItemText(5, _translate("MainWindow", "Swim cap"))
        self.comboBox_category.setItemText(6, _translate("MainWindow", "Pull buoy"))
        self.lineEdit_type.setPlaceholderText(_translate("MainWindow", "Type"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.label_6.setText(_translate("MainWindow", "Size"))
        self.pushButtonOK.setText(_translate("MainWindow", "Save"))
        self.pushButtonOK.setShortcut(_translate("MainWindow", "Return"))
        self.pushButtonClearData.setText(_translate("MainWindow", "Clear"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_add_product), _translate("MainWindow", "Add product"))
        self.button_search_2.setShortcut(_translate("MainWindow", "Return"))
        self.button_save_product_edit.setText(_translate("MainWindow", "Save"))
        self.tableWidget_product.setSortingEnabled(False)
        item = self.tableWidget_product.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_product.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget_product.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget_product.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.tableWidget_product.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Material"))
        item = self.tableWidget_product.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Description"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_search), _translate("MainWindow", "Search"))
        self.button_previous_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+Left"))
        self.pushButton_new_item.setText(_translate("MainWindow", "New"))
        self.pushButton_save_edit_item.setText(_translate("MainWindow", "Save"))
        self.pushButton_save_edit_item.setShortcut(_translate("MainWindow", "Return"))
        self.tableWidget_item.setSortingEnabled(False)
        item = self.tableWidget_item.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_item.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget_item.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Color"))
        item = self.tableWidget_item.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget_item.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Image"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_item), _translate("MainWindow", "item_side"))
import Icons_rc
