# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\copperdai\Desktop\Inventory_swim_store_PhungDaiDong\newItem\ui_newItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(224, 266)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Logo-EAUT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(20, 230, 191, 32))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 205, 210))
        self.frame.setMinimumSize(QtCore.QSize(205, 210))
        self.frame.setMaximumSize(QtCore.QSize(205, 210))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_size = QtWidgets.QComboBox(self.frame)
        self.comboBox_size.setMinimumSize(QtCore.QSize(111, 31))
        self.comboBox_size.setMaximumSize(QtCore.QSize(111, 31))
        self.comboBox_size.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.comboBox_size.setObjectName("comboBox_size")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.verticalLayout.addWidget(self.comboBox_size, 0, QtCore.Qt.AlignRight)
        self.lineEdit_color = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_color.setMinimumSize(QtCore.QSize(111, 31))
        self.lineEdit_color.setMaximumSize(QtCore.QSize(111, 31))
        self.lineEdit_color.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.verticalLayout.addWidget(self.lineEdit_color, 0, QtCore.Qt.AlignRight)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBox_price = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_price.setMinimumSize(QtCore.QSize(111, 31))
        self.doubleSpinBox_price.setMaximumSize(QtCore.QSize(111, 31))
        self.doubleSpinBox_price.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.doubleSpinBox_price.setMinimum(1.0)
        self.doubleSpinBox_price.setMaximum(10000.0)
        self.doubleSpinBox_price.setSingleStep(0.01)
        self.doubleSpinBox_price.setObjectName("doubleSpinBox_price")
        self.horizontalLayout.addWidget(self.doubleSpinBox_price)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_quantity = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_quantity.setMinimumSize(QtCore.QSize(111, 31))
        self.spinBox_quantity.setMaximumSize(QtCore.QSize(111, 31))
        self.spinBox_quantity.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.spinBox_quantity.setMinimum(1)
        self.spinBox_quantity.setMaximum(100000)
        self.spinBox_quantity.setObjectName("spinBox_quantity")
        self.horizontalLayout_2.addWidget(self.spinBox_quantity)
        self.verticalLayout.addWidget(self.widget_2)
        self.pushButton_selectImage = QtWidgets.QPushButton(self.frame)
        self.pushButton_selectImage.setEnabled(True)
        self.pushButton_selectImage.setMinimumSize(QtCore.QSize(111, 31))
        self.pushButton_selectImage.setMaximumSize(QtCore.QSize(111, 31))
        self.pushButton_selectImage.setStyleSheet("\n"
"border-radius: 3px;\n"
"\n"
"border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(0, 0, 0);")
        self.pushButton_selectImage.setObjectName("pushButton_selectImage")
        self.verticalLayout.addWidget(self.pushButton_selectImage, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New item"))
        self.comboBox_size.setItemText(0, _translate("Dialog", "S"))
        self.comboBox_size.setItemText(1, _translate("Dialog", "M"))
        self.comboBox_size.setItemText(2, _translate("Dialog", "L"))
        self.comboBox_size.setItemText(3, _translate("Dialog", "XL"))
        self.comboBox_size.setItemText(4, _translate("Dialog", "XXL"))
        self.comboBox_size.setItemText(5, _translate("Dialog", "UNISIZE"))
        self.lineEdit_color.setPlaceholderText(_translate("Dialog", "Color"))
        self.label.setText(_translate("Dialog", "Price"))
        self.label_2.setText(_translate("Dialog", "Quantity"))
        self.pushButton_selectImage.setText(_translate("Dialog", "Select image"))
import Icons_rc
